apiVersion: apps/v1
kind: Deployment
metadata:
  name: cowrie-deployment
  labels:
    app: cowrie
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cowrie
  template:
    metadata:
      labels:
        app: cowrie
    spec:
      containers:
      - name: cowrie
        image: ghcr.io/brianlechthaler/cloud-native-honeypots/cowrie
        ports:
        - containerPort: 2222